debug: 0 # 忽略已存在的数据，重新生成
seed: 43
# seed: 29
device: gpu

# preprocess
user_min: 10 # user_min小于1时，可能导致训练集id不连续，报错
item_min: 10
test_ratio: 0.2

#model
rec_model: CDAE  # MF NeuMF LightGCN SGL CDAE

# task
task_type: ranking  # rating, ranking
exp2imp_threshold: 3.5 # 将评分数据转换为隐式数据的阈值，小于该值的评分数据将被删除

# attack
# rating类支持 none, RandomAttack, AverageAttack, LoveHate, AUSH, RevAdv; 
# ranking类支持 none, RandomAttack, BandwagonAttack, AUSH, RevAdv
attack_model: RevAdv 
target_item_strategy: random # popular, random


#dataset
# rank:

# data_name: ml-100k 
# attacker_num: 180
# filler_num: 50
# target_num: 1

# data_name: ml-1m
# attacker_num: 1200
# filler_num: 76
# target_num: 5

# data_name: CiaoDVD
# attacker_num: 40
# filler_num: 18
# target_num: 1


data_name: lastfm
attacker_num: 290
filler_num: 33
target_num: 2



#rating

# data_name: ml-100k 
# attacker_num: 200
# filler_num: 80
# target_num: 100

# data_name: ml-1m
# attacker_num: 1500
# filler_num: 120
# target_num: 500

# data_name: CiaoDVD
# attacker_num: 150
# filler_num: 20
# target_num: 50


# data_name: yelp2022
# attacker_num: 8000
# filler_num: 5
# target_num: 1000

# data_name: tt
# attacker_num: 10
# filler_num: 1
# target_num: 2




# data_name: Gowalla
# attacker_num: 10
# filler_num: 1
# target_num: 2

