rating:
  # train
  epochs: 9999999
  train_batch_size: 8192
  learning_rate: 0.001
  stopping_step: 50
  stopping_metric: MAE            # (str) The evaluation metric for early stopping. 
  stopping_bigger: False       # (bool) Whether to take a bigger valid metric value as a better result.

  # eval
  eval_batch_size: 16384
  metric_decimal_place: 4
  metrics: ['rmse','mae']


ranking:
  # train
  epochs: 9999999
  train_batch_size: 16384    # 8192 16384
  learning_rate: 0.001
  stopping_step: 40
  stopping_metric: Recall@50            # (str) The evaluation metric for early stopping. 
  stopping_bigger: True       # (bool) Whether to take a bigger valid metric value as a better result.

  # eval
  eval_batch_size: 8192 # 1024
  metric_decimal_place: 4
  topk: [10,50]
  metrics: [ ndcg,  Hit, Recall]